name 'aspyatkin-com'
description 'Installs and configures aspyatkin.com'
version '1.4.0'

recipe 'aspyatkin-com', 'Installs and configures aspyatkin.com'
depends 'latest-git', '~> 1.1.11'
depends 'latest-nodejs', '~> 1.2.7'
depends 'modern_nginx', '~> 1.3.0'
depends 'rbenv', '~> 1.7.1'
depends 'ssh_known_hosts', '~> 4.0.0'
depends 'ssh-private-keys', '~> 1.0.0'
depends 'tls', '~> 2.0.0'
depends 'poise-python', '1.5.1'
